<?php

	require DIR_UNITS . 'composition/admin/composition.controller.inc';
	require DIR_UNITS . 'general/admin/general.controller.inc';
	require DIR_UNITS . 'users/admin/users.controller.inc';
	require DIR_UNITS . 'statistics/admin/statistics.controller.inc';
    require DIR_UNITS . 'travel/admin/travel.controller.inc';
    require DIR_UNITS . 'people/admin/people.controller.inc';
    require DIR_UNITS . 'photo/admin/photo.controller.inc';
    require DIR_UNITS . 'story/admin/story.controller.inc';
    require DIR_UNITS . 'review/admin/review.controller.inc';
	require DIR_UNITS . 'feedback/admin/feedback.controller.inc';
	require DIR_UNITS . 'pages/admin/pages.controller.inc';