<?php

	require DIR_UNITS . 'general/admin/general.inc';
    require DIR_UNITS . 'tour/admin/tours.inc';
    require DIR_UNITS . 'people/admin/people.inc';
    require DIR_UNITS . 'photo/admin/photo.inc';
    require DIR_UNITS . 'story/admin/story.inc';
    require DIR_UNITS . 'review/admin/reviews.inc';
    require DIR_UNITS . 'feedback/admin/feedback.inc';
//    require DIR_UNITS . 'tour/admin/types.inc';
