<?php

	namespace Proj\Editor\Consts;

	const ID_USER_GROUPS			= 1001;
	const ID_USER_USERS				= 1002;
	const ID_USER_ACCESS_GROUPS		= 1003;
	const ID_USER_ACCESS_USERS		= 1004;
	const ID_STATISTICS_IP			= 1005;
	const ID_STATISTICS_ACTIONS		= 1006;
	const ID_GENERAL_TEXT			= 1010;
	const ID_GENERAL_IMAGE			= 1011;
	const ID_REVIEW     			= 1012;
	const ID_PEOPLE     			= 1013;
	const ID_TOUR_TYPE     			= 1014;
	const ID_TOUR_DIRECTION    		= 1015;
	const ID_TOUR    			    = 1016;
	const ID_PHOTO    			    = 1017;
	const ID_FEEDBACK               = 1018;
	const ID_STORY                  = 1019;