<?php

	require DIR_UNITS . 'users/site/users.controller.inc';
	require DIR_UNITS . 'statistics/site/statistics.controller.inc';
	require DIR_UNITS . 'general/site/general.controller.inc';
	require DIR_UNITS . 'feedback/site/feedback.controller.inc';
	require DIR_UNITS . 'travel/site/travel.controller.inc';
	require DIR_UNITS . 'photo/site/photo.controller.inc';
	require DIR_UNITS . 'people/site/people.controller.inc';
	require DIR_UNITS . 'story/site/story.controller.inc';
	require DIR_UNITS . 'review/site/review.controller.inc';
	require DIR_UNITS . 'pages/site/pages.controller.inc';