<?php

//	require 'general/site/general.inc';
//	require 'users/site/users.inc';
//	require 'statistics/site/statistics.inc';
//	require 'catalogs/site/catalogs.inc';
	require DIR_UNITS . 'general/site/general.inc';
	require DIR_UNITS . 'tour_types/site/tour_types.inc';
	require DIR_UNITS . 'feedback/site/feedback.inc';
	require DIR_UNITS . 'reviews/site/reviews.inc';
	require DIR_UNITS . 'people/site/people.inc';
	require DIR_UNITS . 'stories/site/stories.inc';
