<?php

	namespace Base\DB\MySQLi;

	class FieldUInt8 extends Field {
		public function __construct(string $name, Table $table) {
			parent::__construct('uint8', $name, $table);

			$this->_type = ['tinyint unsigned', 'tinyint(3) unsigned'];
			$this->_null = 'NO';
			$this->_key = '';
			$this->_default = '0';
			$this->_extra = '';
		}

		private function GetFormat(): string { return "`{$this->name}` tinyint(3) unsigned NOT NULL DEFAULT '0'"; }

		public function CreationFormat(): string { return $this->GetFormat(); }
		public function UpdatingFormat(): string { return $this->GetFormat(); }

	}