<?php

    require DIR_BASE . 'versionsControl.inc';
	require DIR_BASE . 'versions.inc';
	require DIR_BASE . 'functions.inc';
	require DIR_BASE . 'others/UploaderImage.inc';

	require DIR_BASE . 'instance.inc';
	require DIR_BASE . 'stage.inc';
	require DIR_BASE . 'controller.inc';
	require DIR_BASE . 'action.inc';
	require DIR_BASE . 'units.inc';

	require DIR_BASE . 'template/layout.inc';
	require DIR_BASE . 'template/section.inc';
	require DIR_BASE . 'template/buffering.inc';
	require DIR_BASE . 'template/template.inc';
