<?php

	namespace Proj;

	use Base\DB\DBQueryMySQLi;

	class DBQuery extends DBQueryMySQLi {

		public function __construct($hostname, $user, $password, $dbname) {
			parent::__construct($hostname, $user, $password, $dbname);
		}

	}

	DBQuery::init(DB_HOST, DB_USER, DB_PASS, DB_NAME);

	if (!DBQuery::instance()->State()) die('MySQLi database connection error! Code: ' . DBQuery::instance()->GetErrorCode());